class ConstString {
  static const String apiURL = "https://www.omdbapi.com";
  static const String projectTitle = 'Movie Browser';
  static const String apiSearchByTitleHeader = "/?t=";
  static const String apiSearchByWordHeader = "/?s=";
  static const String pageHeader = "&page=";
  static const String apiKeyHeader = "&apikey=";
  static const String englishLocale = 'en';
  static const String polishLocale = 'pl';
  static const String hiveSearchHistoryBoxName = 'search_history';
  static const String hiveMoviesBox = 'movies';
  static const String apiResponseHeader = 'Response';
  static const String apiFalseResponse = 'False';
  static const String apiTrueResponse = 'True';
  static const String apiErrorResponse = 'Error';
  static const String connectionErrorMessageDefault = "Connection Error!";
  static const String apiMovieNotFoundResponse = 'Movie not found!';
  static const String apiMovieSearchResponse = 'Search';
  static const String apiMovieSourceResponse = 'Source';
  static const String apiMovieRatingsValueResponse = 'Value';
  static const String connectionErrorNoData = "NO DATA";
  static const String apiMovieImdbIDHeader = 'imdbID';
  static const String apiMovieYearHeader = 'Year';
  static const String apiMovieTypeHeader = 'Type';
  static const String apiMoviePosterHeader = 'Poster';
  static const String apiMovieRatingsHeader = 'Ratings';
  static const String apiMovieReleaseDateHeader = 'Released';
  static const String apiMovieRunTimeHeader = 'Runtime';
  static const String apiMovieRatedHeader = 'Rated';
  static const String apiMovieGenreHeader = 'Genre';
  static const String apiMovieWriterHeader = 'Writer';
  static const String apiMovieActorsHeader = 'Actors';
  static const String apiMoviePlotHeader = 'Plot';
  static const String apiMovieLanguageHeader = 'Language';
  static const String apiMovieCountryHeader = 'Country';
  static const String apiMovieAwardsHeader = 'Awards';
  static const String apiMovieMetascoreHeader = 'Metascore';
  static const String apiMovieDirectorHeader = 'Director';
  static const String apiMovieImdbRatingHeader = 'imdbRating';
  static const String apiMovieImdbVotesHeader = 'imdbVotes';
  static const String apiMovieProductionHeader = 'Production';
  static const String apiMovieDVDHeader = 'DVD';
  static const String apiMovieWebsiteHeader = 'Website';
  static const String apiMovieNonApplicableHeader = "N/A";
  static const String apiMovieBoxOfficeHeader = 'BoxOffice';
  static const String apiMovieTitleHeader = 'Title';
  static const String connectionMessageHeader = 'message';
  static const String connectionMessageDefaultMessage = 'Unknown API error';
  static const String connectionMessageApiErrorMessage = 'API error';
  static const String connectionMessageUnknownErrorMessage = "UNKNOWN ERROR";

  //! TODO THIS IS BAD PRACTICE THAT COULD GET YOU HACKED DONT DO REMOVE LATER BEFORE SUBMITTING
  static const String apiKey = "";
}
